### ISSUE TITLE
WebSocket plugin has been deprecated from the Asset Store

### ISSUE THREAD

**Issue by rajshekarreddy97** [aldiazj/Cortex-Implementation-For-Unity#7]
Are there any other alternatives? 
Thank you.

**Comment by aldiazj** [comment]
Sure! There are other options on the asset store that lets you connect to web sockets, I haven't tried any yet, I'll update the repository then and also the article.

**Comment by rajshekarreddy97** [comment]
If it's not too much trouble could you share the plugin you have till you update the repo? I'd like to get started on the project right away!

**Comment by aldiazj** [comment]
Here you go!
https://drive.google.com/open?id=1JDD0sg8zZgOQfs3pMxFcLLTvzNoi9vYn

**Comment by rajshekarreddy97** [comment]
Thanks!
